name: BookTrack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: booktrack_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, zip
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Prepare environment
      run: |
        cp .env.example .env
        mkdir -p web/uploads/books

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          mysql -h127.0.0.1 -uroot -proot -e "SELECT 1" && break || sleep 2
        done

    - name: Run database migrations
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: booktrack_test
        DB_USERNAME: root
        DB_PASSWORD: root
        YII_ENV: test
        YII_DEBUG: false
      run: php yii migrate --interactive=0

    - name: Run PHPStan
      run: composer stan

    - name: Run CodeSniffer
      run: composer cs

    - name: Run tests
      run: composer test
